# Generated by Django 5.2.8 on 2025-11-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='activation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='decorations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='event_type',
            field=models.CharField(blank=True, choices=[('cumpleaños', 'Cumpleaños'), ('aniversario', 'Aniversario'), ('santo', 'Santo'), ('graduación', 'Graduación'), ('boda', 'Boda'), ('compromiso', 'Compromiso'), ('bautizo', 'Bautizo'), ('primera_comunion', 'Primera Comunión'), ('jubilación', 'Jubilación')], max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='gift_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_gender',
            field=models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('sin genero', 'Prefiero no decirlo')], max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.code'),
        ),
        migrations.AlterField(
            model_name='message',
            name='max_views',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
