# Generated by Django 5.2.4 on 2025-11-26 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_message_user_message_message_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('background_class', models.CharField(default='bg-gray-50', max_length=100)),
                ('primary_text_class', models.CharField(default='text-gray-800', max_length=100)),
                ('accent_class', models.CharField(default='bg-gray-600', max_length=100)),
                ('card_class', models.CharField(default='bg-white', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='decorations',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='activation_datetime',
        ),
        migrations.RemoveField(
            model_name='message',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='gift_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_style',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_gender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.code'),
        ),
        migrations.AlterField(
            model_name='message',
            name='max_views',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
