# Generated by Django 5.2.8 on 2025-11-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_proveedor_address_proveedor_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='secondary_text_class',
            field=models.CharField(default='text-gray-600', max_length=100),
        ),
    ]
